# Generated by Django 4.1.4 on 2022-12-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('module', models.CharField(choices=[('1', 'Gestion Admin.'), ('2', 'Gestion Tech.'), ('3', 'Gestion A.S.S.'), ('4', 'Gestion Imm.'), ('5', 'Cestion Plac.')], default=('1', 'Gestion Admin.'), max_length=100)),
                ('prevision', models.DecimalField(decimal_places=2, max_digits=14)),
                ('executed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('prevision', models.DecimalField(decimal_places=2, max_digits=14)),
                ('executed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.compte')),
            ],
        ),
    ]
