# Generated by Django 4.1.4 on 2022-12-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='module',
            field=models.CharField(choices=[('1', 'Gestion Admin.'), ('2', 'Gestion Tech.'), ('3', 'Gestion A.S.S.'), ('4', 'Gestion Imm.'), ('5', 'Cestion Plac.')], default=1, max_length=100),
        ),
    ]
