# Generated by Django 4.1.4 on 2022-12-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_compte_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='module',
            field=models.IntegerField(),
        ),
    ]
