# Generated by Django 4.1.4 on 2023-01-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_compte_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='executed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, verbose_name='Total Eng.'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='module',
            field=models.IntegerField(verbose_name='Gestion'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='prevision',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Crédit ouvert'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='executed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, verbose_name='Total Eng.'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='prevision',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Crédit ouvert'),
        ),
    ]
