# Generated by Django 4.1.4 on 2022-12-29 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_number', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('purchase_order', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('anterior_engagement', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('total_engagement', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('total_expense', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('available_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('open_credit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(max_length=100)),
                ('module', models.CharField(default=1, max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.ligne')),
            ],
        ),
    ]
